### ISSUE TITLE
bug - Data Hosts Tracking (splk-dhm) - truncation in trackme:state for entities with a very large amount of related sourcetypes

### ISSUE THREAD

**Issue by harv-qq** [trackme-limited/trackme-report-issues#177]
**Describe the bug**
Trackme is installed on the Monitoring Console, Truncating looks to be happening for sourcetype="trackme:state" source="*splk-dhm*" logs in the summary index, hosts seem to produce long json blocks but the max length seems to be stuck at 9768 characters being injested, there is **NO** logs indicating truncating happening at the parsing phase for example 

_06-21-2023 12:26:37.833 +0000 WARN  LineBreakingProcessor [94915 parsing_1] - Truncating line because limit of 10000 bytes has been exceeded with a line length >= 10043............_

Have manually set TRUNCATE=999999 for sourcetype="trackme:state" and makes no difference

Because it is being truncated it is missing from after about halfway through "status_message" including the closing json brackets.

**TrackMe version**
2.0.38

**To Reproduce**
setup to pull in splk-dhm 

**Expected behavior**
the full JSON to be ingested without truncating

**Screenshots**
N/A

**Splunk version and deployment:**

Splunk Version: 9.0.4.1
Installed on dedicatyed monitoring console

**Comment by guilhemmarchand** [comment]
Thank you @harv-qq 
This will be reviewed carefully and shortly, this sounds suspiscious and definitvely doesn't happen as far we know in a non DMC host.

We will keep you posted

**Comment by guilhemmarchand** [comment]
@harv-qq 

You probably have a few hosts with a huge number of sourcetypes that is linked to it, althrough TrackMe should not truncate, it is probably indicating also something that you should probably not be monitoring like that.

You can identify this host from the collection:

```
| inputlookup trackme_dhm_tenant_feeds-tracking
| makemv delim="," data_sourcetype
| stats dc(data_sourcetype) as dcount by object
| sort 0 - dcount
```

Have a look please and let me know your findings.

Also, regarding the truncation, here is the way it works:

props.conf

```
#
# TrackMe events
#

[source::...trackme_state_events.log]
KV_MODE = auto
sourcetype = trackme:state
SHOULD_LINEMERGE=false
LINE_BREAKER=([\r\n]+)\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}
CHARSET=UTF-8
TIME_PREFIX=^
TIME_FORMAT=%Y-%m-%d %H:%M:%S,%3N
TRUNCATE=0

TRANSFORMS-eventslog = trackme_events_001_index_redirect,trackme_events_002_sourcetype_redirect,trackme_events_003_source_redirect,trackme_events_004_raw
```

Using transforms, we extract the _raw event from the log file we write to, in Python, this transform:

```
[trackme_events_004_raw]
LOOKAHEAD = 10000
DEST_KEY = _raw
FORMAT = $1
REGEX = event=(.*)
```

This is probably where the issue stands - the reason why you do not have things in the props definition is not because TrackMe wouldn't do it right practice (of course not) but because we handle it at the source level instead.

Will try to produce, I guess we might reaching a limit there

**Comment by harv-qq** [comment]
Yep cheers for that info. Increasing the LOOKAHEAD in the transforms resolved the issue (doubled for now)

/opt/splunk/etc/apps/trackme/local/transforms.conf

[trackme_events_004_raw]
LOOKAHEAD = 20000
