### ISSUE TITLE
TrackMe bug report - entity status flipping to green and back when it should remain red

### ISSUE THREAD

**Issue by bdcrandall** [trackme-limited/trackme-report-issues#510]
**Describe the bug**
Multiple entities that are correctly red are flipping back to green every 4 hours, then flipping back to red and triggering a new alert.

**TrackMe version**
2.0.83

**To Reproduce**
Configure entity with latency threshold 1800 and delay threshold 86400.  Allow the entity to turn red due to the delay threshold being exceeded, then look for status flipping events.

I'm not sure if this matters but I have changed the ownership of all the saved searches that Trackme runs from admin/nobody to a custom user with the sc_admin role so that when setting hours range monitoring in the UI I can use my local TZ instead of having to convert to UTC.

**Expected behavior**
Entity should remain red until thresholds are met.

**Screenshots**
![TrackMe bug 2024_02_26](https://github.com/trackme-limited/trackme-report-issues/assets/66020496/4fc25b6c-d972-4bdb-b1d7-42b3af460493)

**Splunk version and deployment:**
Splunk Cloud
Version: 9.0.2303.201
Build: 5480631d4591
Experience: Classic
Standalone search head

**Additional context**
Event contents from screenshot in text format:

{"status_message": "Monitoring conditions are not met due to delay issues. Event delay is 169768.0 seconds (duration: 1+23:09:28), which is higher than the maximum allowed delay of 86400 seconds (duration: 1+00:00:00), latest event available (_time) for this entity: 24 Feb 2024 05:03, latest event ingested (_indextime) for this entity: 24 Feb 2024 05:03", "anomaly_reason": "delay_threshold_breached", "object": "operational_logs_30:infoblox:hostrecords", "tenant_id": "fdic-all-data-feeds", "priority": "high", "alias": "operational_logs_30:infoblox:hostrecords", "object_category": "splk-dsm", "key": "9d75b5d422c756fec9ec093ad2acc5f3"}

{"timeStr": "26/02/2024 03:57:26", "tenant_id": "fdic-all-data-feeds", "object": "operational_logs_30:infoblox:hostrecords", "object_category": "splk-dsm", "object_state": "green", "object_previous_state": "red", "latest_flip_time": 1708937846.4982524, "latest_flip_state": "green", "result": "26/02/2024 03:57:26, object=operational_logs_30:infoblox:hostrecords has flipped from previous_state=red to state=green with anomaly_reason=none"}

{"status_message": "Monitoring conditions are not met due to delay issues. Event delay is 168568.0 seconds (duration: 1+22:49:28), which is higher than the maximum allowed delay of 86400 seconds (duration: 1+00:00:00), latest event available (_time) for this entity: 24 Feb 2024 05:03, latest event ingested (_indextime) for this entity: 24 Feb 2024 05:03", "anomaly_reason": "delay_threshold_breached", "object": "operational_logs_30:infoblox:hostrecords", "tenant_id": "fdic-all-data-feeds", "priority": "high", "alias": "operational_logs_30:infoblox:hostrecords", "object_category": "splk-dsm", "key": "9d75b5d422c756fec9ec093ad2acc5f3"}

**Comment by guilhemmarchand** [comment]
Hi @bdcrandall 

Sorry for late replying, we're working hard on TrackMe 2.0.84 ;-)

Hum right - that sounds interesting, every 4 hours you say, this obviously corresponds to the earliest time range of your trackers I imagine.

This sounds like it is related to the health tracker and your change of ownership and TZ, basically the healthcheck tracker is a scheduled per tenant which would be called: trackme_health_tracker_tenant_<tenant_id>

How did you change the ownership? You have to used the RBAC TrackMe re-assignment such that TrackMe handles the re-assignment for all objects properly.

Ideally, I would more advise that the service account runs in UTC, we can however register an enhancement requests so that the hours ranges you specify can be specified in your own TZ and converted automatically to UTC.

I am keen to think that you properly re-assigned via Splunk Web and now you have the health tracker running as nobody while others are running with your service account? (thus causing this)

**Comment by sebwurl** [comment]
Have you checked the delay threshold, did it change? 4h sounds like the adaptive delay could have made changes.
Initial delay breached > red state > adaptive delay changes threshold > green state > new delay breached > red state > adaptive delay changes theshold > ...

**Comment by guilhemmarchand** [comment]
Are we still facing issues here @bdcrandall ?

**Comment by bdcrandall** [comment]
I reassigned all the saved searches back to user Nobody and I haven't seen this behavior in a while.  I think this issue can be closed and I'll reopen or open a new one if it returns.
