### ISSUE TITLE
TrackMe bug report - ~40K lookup files created by app

### ISSUE THREAD

**Issue by bdcrandall** [trackme-limited/trackme-report-issues#537]
**Describe the bug**
App has created an alarming number of lookup table files.  If I attempt to view the Health Overview dashboard in the Lookup Editor app, it slows the search head to the point where it is unusable and requires a full restart to recover.

**TrackMe version**
2.0.83

**To Reproduce**
Set up Trackme for a reasonably large enterprise with ~500 data sources and ~20K data hosts.  Go to the Splunk App for Lookup File Editing and then click on Health -> Overview.

**Expected behavior**
Dashboard should load.  I'm reporting this issue to Splunk as well in case the problem is the lookup editor app.

**Screenshots**
Here's a search that shows how many lookup table files Trackme has generated.  All but one are .mlmodel files.
![Trackme_lookups](https://github.com/trackme-limited/trackme-report-issues/assets/66020496/159bc8e1-727c-4642-b617-9497171879b9)

**Splunk version and deployment:**
Splunk Cloud
Version: 9.0.2303.201
Build: 5480631d4591
Experience: Classic
Standalone search head

**Additional context**
None

**Comment by guilhemmarchand** [comment]
Hi @bdcrandall 

These are Machine Learning models, in the release 2.0.84 we have addressed this exact issue when ML models created by TrackMe are impacting the load time of the Lookup editor especially as well as introducing an automated cleanup of unused ML models:

https://docs.trackme-solutions.com/latest/releasenotes.html#version-2-0-84-build-1709505402-03-03-2024

```
Schema upgrade for TrackMe version 2.0.84

This release includes a TrackMe schema upgrade which will automatically clean Outliers orphan records and orphan ML models.

The schema upgrade is executed within the next 5 minutes after the upgrade, through the tenant’s health tracker jobs.

If there is a large amount of orphan models to be cleaned up, this can temporarily increase generate skipping searches for the health tracker as its execution would eventually take much longer than usual.

After this, the health tracker will resume its normal execution and skipping searches for it will disappear.

This process is fully automated, and there are no intervention required.
```

Please upgrade to the last vetted release of TrackMe (currently 2.0.85), after the upgrade TrackMe will re-assign the ML models to the splunk-system-user and models are from this version handled as private objects on behalf of the system user, avoiding slowness or blocking while listing lookups in the system.

**Comment by bdcrandall** [comment]
The number of lookups is down to ~3K at this point so that is good.  However, after the upgrade to 2.0.85 the resulting knowledge bundle exceeded the distsearch.conf limit of 3000 MB so it still contains a lot of the orphaned .mlmodel files.  I am waiting for Splunk Cloud support to help me with the knowledge bundle issue before I can confirm that this issue is completely fixed by the upgrade.

**Comment by guilhemmarchand** [comment]
@bdcrandall 

Hum - basically, ml models are not meant to be part of the knowledge bundle, for this purpose, TrackMe always had a distsearch.conf which blocklists the models:

```
# Machine Learning models: Anomaly detection will generate various ML models files, there are not needed on the indexer layers
trackme_mlmodels = apps/trackme/lookups/__mlspl_*.mlmodel
```

However, it is true that since now models are owned by the splunk-system-user, theses files location on the file-system have changed to:

```
users/splunk-system-user/trackme/lookups/__mlspl_*.mlmodel
```

This is a relative path, the root is $SPLUNK_HOME, on Splunk Cloud this is /opt/splunk (which is the default of Splunk, Splunk Cloud is not really different from Splunk Enterprise in reality)

As a Splunk Cloud customer, you totally can publish distsearch configuration to blocklist certain files from the bundle. (you can publish your own config as part of a configuration file in a base config app of yours)

Especially, if you are on Victoria you do not have to dependent on Splunk Cloud customer, in fact you should not.

Final word, the numebr of ML models is not necessary super meaningful, TrackMe manages these models, there was an issue it's true when these models were shared at the app level as these would impact apps like the lookup editor or listing lookups from REST (Splunk Web is a rest client) - which is addressed now.

Nevertheless, I will double check the blocklist question, we totally can add the one I mentioned and I will check if we should.

**Comment by guilhemmarchand** [comment]
For reference:

- change - Machine Learning models management - Ensures privately owned TrackMe ML models from the splunks-system-user are excluded from the Knowledge Bundle replication #545

**Comment by bdcrandall** [comment]
@guilhemmarchand you figured it out.  The lookups clogging up the bundle are all in users/splunk-system-user/trackme/lookups/ but the replicationDenylist is blocking apps/trackme/lookups/.  So I need that bug fix you linked or a custom distsearch.conf.  Sadly I am not on Victoria.

**Comment by guilhemmarchand** [comment]
Fair enough @bdcrandall  ;-)

We are planning to release TrackMe 2.0.87 by the end of the day, then it's about vetting time.

**Comment by bdcrandall** [comment]
I put a temporary replicationDenylist in place and that worked.  Upgraded to v2.0.87 and that fixes the issue as well.
