### ISSUE TITLE
TrackMe bug report - Tracker Performance Deepdive shows suspicious values

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#538]
I checked the **Audit - Tracker Performance Deepdive** to review run times in v.2.0.84.
It shows run times for the DSM Tracker of ~5sec which looks very suspicious. While the search behind the dashboard uses collected metrics, I double checked the scheduler log and it reports an avg of 80s for the hybrid tracker. That seems to be more reasonable.

I used this search to review the runtime with internal logs.
`index=_internal sourcetype=scheduler source=/opt/splunk/var/log/splunk/scheduler.log app=trackme run_time=* (savedsearch_name=trackme_dsm_hybrid_*tracker*)
| timechart span=5m max(run_time) as max_run_time_sec by savedsearch_name`

**Comment by guilhemmarchand** [comment]
Hi @sebwurl 

You are correct, there has been a regression leading to incorrect run time being returned for trackers runtime metrics.

This has been already fixed in the release 2.0.86 which is still pending for Cloud vetting:

https://docs.trackme-solutions.com/latest/releasenotes.html#version-2-0-86-build-1710525022-15-03-2024

trackme-limited/trackme-report-issues#532 - bug - TrackMe performance counters for Trackers report inaccurate measures (trackmetrackerexecutor) #532
