### ISSUE TITLE
TrackMe bug report - DSM blocklisting not working at discovery

### ISSUE THREAD

**Issue by Tinman51** [trackme-limited/trackme-report-issues#578]
The DSM discovery process appears to be ignoring the blocklist values after update from 2.0.83 to 2.0.88. We are getting internal (_audit, _internal etc) and other indexes explicitly listed in the blocklist being added to the DSM_tenant lookup each time it runs. Confirmed proper values exist in the lookup dsm_allowlist_tenant listing as well

TrackMe version
2.0.88

To Reproduce

Open the dsm_allowlist kv lookup and add a filter for index=main
Insert an event into index Main with a new sourcetype
Run discovery job
Open tabulator and view index=main entity objects to see the new sourcetype created in the main index above.

Expected behavior
Discovery should not have inserted a blocklisted index sourcetype to the dsm_tenant lookup

Screenshots
N/A

Splunk version and deployment:
Splunk Cloud Classic - 9.1.2312.102

Provide the Splunk core version
Search Head Cluster (SHC)

Additional context
None

**Comment by guilhemmarchand** [comment]
Hi @Tinman51 

It is true that recently, TrackMe changed some aspects of the discovery process, to avoid confusion and also improve different parts of the process, the discovery is now called blocklist, which is what it is after all, and is fully handled in Python with more flexibility.

However, the blocklist is supposed to be managed at the level of the REST API, either via the UI and the blocklist screen, or via the REST endpoint:

![CleanShot 2024-04-22 at 22 46 03@2x](https://github.com/trackme-limited/trackme-report-issues/assets/7503059/a46fc4d9-7456-42bc-ba4d-c9f50de4f81b)

Say, here we discover all indexes, and I want to add main:

![CleanShot 2024-04-22 at 22 47 15@2x](https://github.com/trackme-limited/trackme-report-issues/assets/7503059/0a07e194-9d43-4c9d-a2fe-a249e73449c8)

Then I also want to exclude all _* indexes:

![CleanShot 2024-04-22 at 22 48 23@2x](https://github.com/trackme-limited/trackme-report-issues/assets/7503059/fbdb307e-df69-46d3-9a68-3674c3aed6ea)

Then the UI will exclude the matching entities automatically:

![CleanShot 2024-04-22 at 22 49 41@2x](https://github.com/trackme-limited/trackme-report-issues/assets/7503059/2d40b7af-9473-4884-9e03-eab111bbe4b2)

However, these entities remain indeed in the KVstore:

![CleanShot 2024-04-22 at 22 50 44@2x](https://github.com/trackme-limited/trackme-report-issues/assets/7503059/01ab280b-6737-4b15-b6da-4e6d6727a149)

But these won't be considered anymore by TrackMe UI, and TrackMe alerts, from recent versions, you can use the command:

```
| trackmegetcoll tenant_id=<mytenant> component=<component>
```

To access the TrackMe entities excactly as considered by Trackme UI and Trackme alerts:

![CleanShot 2024-04-22 at 22 52 33@2x](https://github.com/trackme-limited/trackme-report-issues/assets/7503059/c62aeaa6-6e2a-4770-a6ff-ae34e3c35ae2)

Anything that is not in this output would not be considered de factor by TrackMe - but still considered at the ingest and the record level, because the blocklist is some sorts of a search time activity at the very last stage of rendering the entities.

Blocklists are meant to be used when you CANNOT easily exclude contents at the discovery time by ensuring that you trackers do not look at these indexes, which is of course superior since you avoid the costs of that.

Blocklists are stored in the following KVcollection, and need the associated fields to be considered:

![CleanShot 2024-04-22 at 22 55 57@2x](https://github.com/trackme-limited/trackme-report-issues/assets/7503059/15aed9a4-00e4-4771-b96b-2040b5408960)

Could your issue / confusiong be because you've been manipularting these entries manually, and we do not consider your records because these are not including the fields we normally expect?

**Comment by Tinman51** [comment]
I used the UI as you showed in the screen shots to add/update the blocklist and I have confirmed in the KVStore that the entities are there. 

So I have added an index blocklist entity with a value of "_*" to block all internal splunk indexes from discovery, it doesnt work. Everytime discovery runs, I get new sourcetypes form the _internal or other blocklisted indexes.

I will check my default filters in the tracker, but that wouldnt have changed from prior to upgrading.

**Comment by guilhemmarchand** [comment]
@Tinman51 

TrackMe 2.0.89 is live and will address your issue transparently.
You can either migrate, or modify the blocklists using a regex pattern instead of the simple wildcard as mentioned previously.

Please re-open the issue if you still have any issue

Guilhem
