### ISSUE TITLE
enhancement - In Virtual Tenants & Home UI, show the number of enabled entities rather then total number of entities

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#778]
I would prefer a single value panel in the main dashboard that shows the "enabled" entities, instead of total discovered entities ("data sources" panel). Currently the panel shows disabled + enabled. Basically I'm always interested how many entities are actively monitored and how many are disabled (disabled is already available). This panel would also make it easier to classify the absolute numbers of alert panels at first glance.

![image](https://github.com/user-attachments/assets/db4c7dba-49df-4fe1-b7da-b3d3e46c7350)

**Comment by sebwurl** [comment]
The same would be nice for the panel of the virtual tenant:
![image](https://github.com/user-attachments/assets/daa4e885-053f-4148-9dab-88c354afc23c)

**Comment by guilhemmarchand** [comment]
**enhancement - In Virtual Tenants & Home UI, show the number of enabled entities rather then total number of entities**

- This enhancement updates the number of entities primarly shown in the Virtual Tenants UI, as well as the Home UI and the left single view, so that we show the total number of enabled entities, instead of the total number entities active + inactive.
- This provides more valuable information as well as a better clarity in TrackMe.

**Comment by guilhemmarchand** [comment]
Thank you @sebwurl and agreed on everything ;-)

Live in upcoming 2.1.1
